project_id = "pfmyebdyebglnnmfwuzh"

[functions.chat]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.auth-notification]
verify_jwt = false

[functions.github-sync]
verify_jwt = false
